/* Generated by Yosys 0.9+3710 (git sha1 2116c585, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1606966417886/work=/usr/local/src/conda/yosys-0.9_5007_g2116c585 -fdebug-prefix-map=/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
(* src = "midi_ctrl.sv:9.1-133.10" *)
module midi_ctrl(rst, clk, btn1, btn2, btn3, btn4, led1, led2, midi_tx);
  (* src = "midi_ctrl.sv:0.0-0.0" *)
  wire _000_;
  wire [4:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  (* unused_bits = "0" *)
  wire _007_;
  (* unused_bits = "0" *)
  wire _008_;
  (* unused_bits = "0" *)
  wire _009_;
  (* unused_bits = "0" *)
  wire _010_;
  wire _011_;
  (* unused_bits = "0" *)
  wire _012_;
  (* unused_bits = "0" *)
  wire _013_;
  (* unused_bits = "0" *)
  wire _014_;
  wire _015_;
  (* unused_bits = "0" *)
  wire _016_;
  (* unused_bits = "0" *)
  wire _017_;
  (* unused_bits = "0" *)
  wire _018_;
  (* unused_bits = "0" *)
  wire _019_;
  (* unused_bits = "0" *)
  wire _020_;
  (* unused_bits = "0" *)
  wire _021_;
  (* unused_bits = "0" *)
  wire _022_;
  (* unused_bits = "0" *)
  wire _023_;
  (* unused_bits = "0" *)
  wire _024_;
  wire _025_;
  (* unused_bits = "0" *)
  wire _026_;
  (* unused_bits = "0" *)
  wire _027_;
  (* unused_bits = "0" *)
  wire _028_;
  (* unused_bits = "0" *)
  wire _029_;
  (* unused_bits = "0" *)
  wire _030_;
  (* unused_bits = "0" *)
  wire _031_;
  (* unused_bits = "0" *)
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  (* unused_bits = "0" *)
  wire _038_;
  (* unused_bits = "0" *)
  wire _039_;
  (* unused_bits = "0" *)
  wire _040_;
  (* unused_bits = "0" *)
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  (* invertible_pin = "IS_CLR_INVERTED" *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:644.9-644.12" *)
  wire _090_;
  (* clkbuf_sink = 32'd1 *)
  (* invertible_pin = "IS_C_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:641.9-641.10" *)
  wire _091_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:42.41-42.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:724.9-724.10" *)
  wire _092_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _093_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _094_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _095_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _096_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _097_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _098_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _099_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _100_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _101_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _102_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _103_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _104_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _105_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _106_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _107_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _108_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _109_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _110_;
  (* invertible_pin = "IS_D_INVERTED" *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/cells_sim.v:646.9-646.10" *)
  wire _111_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _112_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _113_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _114_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _115_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _116_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _117_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _118_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _119_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _120_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _121_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _122_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _123_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _124_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _125_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _126_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _127_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _128_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _129_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _130_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _131_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _132_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _133_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _134_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _135_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _136_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _137_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _138_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _139_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _140_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _141_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _142_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _143_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _144_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _145_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _146_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _147_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _148_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _149_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _150_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _151_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _152_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _153_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _154_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _155_;
  (* src = "midi_ctrl.sv:28.7-28.15" *)
  wire baud_clk;
  (* src = "midi_ctrl.sv:13.17-13.21" *)
  input btn1;
  (* src = "midi_ctrl.sv:40.7-40.19" *)
  wire btn1_pressed;
  (* src = "midi_ctrl.sv:14.17-14.21" *)
  input btn2;
  (* src = "midi_ctrl.sv:41.7-41.19" *)
  wire btn2_pressed;
  (* src = "midi_ctrl.sv:15.17-15.21" *)
  input btn3;
  (* src = "midi_ctrl.sv:42.7-42.19" *)
  wire btn3_pressed;
  (* src = "midi_ctrl.sv:16.17-16.21" *)
  input btn4;
  (* src = "midi_ctrl.sv:43.7-43.19" *)
  wire btn4_pressed;
  (* src = "midi_ctrl.sv:39.7-39.18" *)
  wire btn_pressed;
  (* src = "midi_ctrl.sv:44.7-44.16" *)
  wire btn_reset;
  (* src = "midi_ctrl.sv:12.17-12.20" *)
  input clk;
  (* src = "midi_ctrl.sv:35.13-35.18" *)
  wire [7:0] data1;
  (* src = "midi_ctrl.sv:36.13-36.18" *)
  wire [7:0] data2;
  (* src = "midi_ctrl.sv:17.18-17.22" *)
  output led1;
  (* src = "midi_ctrl.sv:18.18-18.22" *)
  output led2;
  (* src = "midi_ctrl.sv:19.18-19.25" *)
  output midi_tx;
  (* src = "midi_ctrl.sv:11.17-11.20" *)
  input rst;
  (* src = "midi_ctrl.sv:34.13-34.19" *)
  wire [7:0] status;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h2)
  ) _156_ (
    .I0(_132_[0]),
    .I1(_121_[1]),
    .O(_109_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h2)
  ) _157_ (
    .I0(_120_[0]),
    .I1(_121_[1]),
    .O(_105_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h2)
  ) _158_ (
    .I0(_130_[0]),
    .I1(_121_[1]),
    .O(_108_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h32)
  ) _159_ (
    .I0(btn2_pressed),
    .I1(btn1_pressed),
    .I2(btn3_pressed),
    .O(_001_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _160_ (
    .I0(btn2_pressed),
    .I1(btn1_pressed),
    .O(_001_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2)
  ) _161_ (
    .I0(_097_),
    .I1(_112_[1]),
    .I2(_112_[2]),
    .I3(_112_[3]),
    .I4(_112_[4]),
    .O(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _162_ (
    .I0(_119_[0]),
    .I1(_119_[1]),
    .I2(_119_[2]),
    .O(_120_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _163_ (
    .I0(_118_[0]),
    .I1(_118_[1]),
    .O(_120_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h2)
  ) _164_ (
    .I0(btn_pressed),
    .I1(_113_[2]),
    .O(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _165_ (
    .I0(btn4_pressed),
    .I1(btn_reset),
    .I2(btn3_pressed),
    .I3(_124_[3]),
    .O(_153_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd134217728)
  ) _166_ (
    .I0(_120_[0]),
    .I1(_120_[1]),
    .I2(_120_[2]),
    .I3(_120_[3]),
    .I4(_120_[4]),
    .O(_121_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _167_ (
    .I(btn_reset),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _168_ (
    .I(_150_),
    .O(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _169_ (
    .I(_151_),
    .O(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _170_ (
    .I(_112_[4]),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _171_ (
    .I(_112_[3]),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _172_ (
    .I(_112_[2]),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _173_ (
    .I(_112_[1]),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _174_ (
    .I(_152_),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'hd)
  ) _175_ (
    .I0(btn3_pressed),
    .I1(_124_[3]),
    .O(_001_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _176_ (
    .I0(btn_reset),
    .I1(_153_[1]),
    .O(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _177_ (
    .I0(btn2_pressed),
    .I1(btn1_pressed),
    .O(_124_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _178_ (
    .I0(btn_pressed),
    .I1(_113_[2]),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4294967293)
  ) _179_ (
    .I0(_097_),
    .I1(_112_[1]),
    .I2(_112_[2]),
    .I3(_112_[3]),
    .I4(_112_[4]),
    .O(_113_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:56.20-56.31|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5" *)
  CARRY4 _180_ (
    .CI(1'h0),
    .CO({ _011_, _010_, _009_, _008_ }),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O({ _102_, _101_, _100_, _007_ }),
    .S({ _006_, _005_, _004_, _094_ })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:56.20-56.31|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8" *)
  CARRY4 _181_ (
    .CI(_011_),
    .CO({ _015_, _014_, _013_, _012_ }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _106_, _120_[0], _104_, _103_ }),
    .S({ _118_[0], _118_[1], _003_, _002_ })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:56.20-56.31|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8" *)
  CARRY4 _182_ (
    .CI(_015_),
    .CO({ _025_, _024_, _023_, _022_ }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _110_, _132_[0], _130_[0], _107_ }),
    .S({ _119_[1], _119_[2], _120_[1], _120_[2] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:56.20-56.31|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8" *)
  CARRY4 _183_ (
    .CI(_025_),
    .CO({ _032_, _031_, _030_, _029_ }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _028_, _027_, _026_, _111_ }),
    .S({ 3'h0, _119_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:116.21-116.33|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5" *)
  CARRY4 _184_ (
    .CI(1'h0),
    .CO({ _042_, _041_, _040_, _039_ }),
    .CYINIT(1'h1),
    .DI({ _112_[3], _112_[4], _152_, _125_[0] }),
    .O({ _098_, _097_, _096_, _038_ }),
    .S({ _034_, _033_, _037_, _125_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:116.21-116.33|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8" *)
  CARRY4 _185_ (
    .CI(_042_),
    .CO({ _021_, _020_, _019_, _018_ }),
    .CYINIT(1'h0),
    .DI({ 2'h0, _112_[1], _112_[2] }),
    .O({ _017_, _016_, _122_[0], _099_ }),
    .S({ 2'h0, _036_, _035_ })
  );
  BUFG _186_ (
    .I(_051_),
    .O(_046_)
  );
  BUFG _187_ (
    .I(_052_),
    .O(_047_)
  );
  BUFG _188_ (
    .I(_053_),
    .O(_048_)
  );
  BUFG _189_ (
    .I(_054_),
    .O(_049_)
  );
  BUFG _190_ (
    .I(_055_),
    .O(_091_)
  );
  BUFG _191_ (
    .I(_056_),
    .O(baud_clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:72.1-74.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _192_ (
    .C(_049_),
    .CE(1'h1),
    .D(_049_),
    .Q(btn4_pressed),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:68.1-70.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _193_ (
    .C(_048_),
    .CE(1'h1),
    .D(_048_),
    .Q(btn3_pressed),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:64.1-66.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _194_ (
    .C(_047_),
    .CE(1'h1),
    .D(_047_),
    .Q(btn2_pressed),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:60.1-62.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _195_ (
    .C(_046_),
    .CE(1'h1),
    .D(_046_),
    .Q(btn1_pressed),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _196_ (
    .C(baud_clk),
    .CE(_113_[2]),
    .D(btn_pressed),
    .Q(btn_reset),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _197_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_094_),
    .Q(_151_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _198_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_100_),
    .Q(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _199_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_101_),
    .Q(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _200_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_102_),
    .Q(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _201_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_103_),
    .Q(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _202_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_104_),
    .Q(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _203_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_105_),
    .Q(_118_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _204_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_106_),
    .Q(_118_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _205_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_107_),
    .Q(_120_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _206_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_108_),
    .Q(_120_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _207_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_109_),
    .Q(_119_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _208_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_110_),
    .Q(_119_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _209_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_111_),
    .Q(_119_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:46.1-58.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _210_ (
    .C(_091_),
    .CE(1'h1),
    .CLR(_090_),
    .D(_057_),
    .Q(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _211_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_058_),
    .Q(_155_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _212_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_059_),
    .Q(_126_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _213_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_060_),
    .Q(_129_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _214_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_061_),
    .Q(_114_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _215_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_062_),
    .Q(_115_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _216_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_063_),
    .Q(_128_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _217_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_064_),
    .Q(_123_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _218_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_065_),
    .Q(_117_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _219_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_066_),
    .Q(_116_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _220_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_067_),
    .Q(_113_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _221_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_068_),
    .Q(_149_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _222_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_069_),
    .Q(_131_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _223_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_070_),
    .Q(_133_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _224_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_071_),
    .Q(_134_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _225_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_072_),
    .Q(_135_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _226_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_073_),
    .Q(_136_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _227_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_074_),
    .Q(_137_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _228_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_075_),
    .Q(_138_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _229_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_076_),
    .Q(_139_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _230_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_077_),
    .Q(_140_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _231_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_078_),
    .Q(_154_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _232_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_079_),
    .Q(_141_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _233_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_080_),
    .Q(_142_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _234_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_081_),
    .Q(_143_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _235_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_082_),
    .Q(_144_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _236_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_083_),
    .Q(_145_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _237_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_084_),
    .Q(_146_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _238_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_085_),
    .Q(_147_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _239_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_086_),
    .Q(_148_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h0)
  ) _240_ (
    .C(baud_clk),
    .CE(_043_),
    .CLR(_090_),
    .D(_095_),
    .Q(_127_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _241_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_087_),
    .Q(_125_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _242_ (
    .C(baud_clk),
    .CE(_043_),
    .CLR(_090_),
    .D(_096_),
    .Q(_152_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _243_ (
    .C(baud_clk),
    .CE(_043_),
    .CLR(_090_),
    .D(_097_),
    .Q(_112_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _244_ (
    .C(baud_clk),
    .CE(_043_),
    .CLR(_090_),
    .D(_098_),
    .Q(_112_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _245_ (
    .C(baud_clk),
    .CE(_043_),
    .CLR(_090_),
    .D(_099_),
    .Q(_112_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _246_ (
    .C(baud_clk),
    .CE(1'h1),
    .CLR(_090_),
    .D(_088_),
    .Q(_112_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'h1)
  ) _247_ (
    .C(baud_clk),
    .CE(_044_),
    .CLR(_090_),
    .D(_093_),
    .Q(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:42.41-42.97" *)
  FDPE #(
    .INIT(1'h0)
  ) _248_ (
    .C(baud_clk),
    .CE(1'h1),
    .D(_089_),
    .PRE(_090_),
    .Q(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:105.1-131.4|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:42.41-42.97" *)
  FDPE #(
    .INIT(1'h0)
  ) _249_ (
    .C(baud_clk),
    .CE(_044_),
    .D(_092_),
    .PRE(_090_),
    .Q(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:0.0-0.0|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:87.61-87.120" *)
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _250_ (
    .CLR(1'h0),
    .D(1'h1),
    .G(_045_),
    .GE(1'h1),
    .Q(status[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:0.0-0.0|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:87.61-87.120" *)
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _251_ (
    .CLR(1'h0),
    .D(_001_[0]),
    .G(_045_),
    .GE(1'h1),
    .Q(data1[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:0.0-0.0|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:87.61-87.120" *)
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _252_ (
    .CLR(1'h0),
    .D(_001_[1]),
    .G(_045_),
    .GE(1'h1),
    .Q(data1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:0.0-0.0|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:87.61-87.120" *)
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _253_ (
    .CLR(1'h0),
    .D(_124_[3]),
    .G(_045_),
    .GE(1'h1),
    .Q(data1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:0.0-0.0|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:87.61-87.120" *)
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _254_ (
    .CLR(1'h0),
    .D(_001_[4]),
    .G(_045_),
    .GE(1'h1),
    .Q(data1[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "midi_ctrl.sv:0.0-0.0|/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/ff_map.v:87.61-87.120" *)
  LDCE #(
    .INIT(1'h0),
    .IS_G_INVERTED(1'h1)
  ) _255_ (
    .CLR(1'h0),
    .D(_000_),
    .G(_153_[1]),
    .GE(1'h1),
    .Q(btn_pressed)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT3 #(
    .INIT(8'h34)
  ) _256_ (
    .I0(btn_pressed),
    .I1(_125_[0]),
    .I2(_113_[2]),
    .O(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _257_ (
    .I0(_155_[0]),
    .I1(btn_pressed),
    .I2(_126_[0]),
    .I3(_113_[2]),
    .O(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _258_ (
    .I0(_126_[0]),
    .I1(btn_pressed),
    .I2(_129_[0]),
    .I3(_113_[2]),
    .O(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _259_ (
    .I0(_129_[0]),
    .I1(btn_pressed),
    .I2(_114_[0]),
    .I3(_113_[2]),
    .O(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _260_ (
    .I0(_114_[0]),
    .I1(btn_pressed),
    .I2(_115_[0]),
    .I3(_113_[2]),
    .O(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _261_ (
    .I0(_115_[0]),
    .I1(btn_pressed),
    .I2(_128_[0]),
    .I3(_113_[2]),
    .O(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _262_ (
    .I0(_117_[1]),
    .I1(btn_pressed),
    .I2(_116_[0]),
    .I3(_113_[2]),
    .O(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf0ee)
  ) _263_ (
    .I0(_113_[1]),
    .I1(btn_pressed),
    .I2(_149_[0]),
    .I3(_113_[2]),
    .O(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _264_ (
    .I0(_149_[0]),
    .I1(btn_pressed),
    .I2(_131_[0]),
    .I3(_113_[2]),
    .O(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _265_ (
    .I0(_138_[1]),
    .I1(btn_pressed),
    .I2(_139_[0]),
    .I3(_113_[2]),
    .O(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _266_ (
    .I0(_139_[0]),
    .I1(btn_pressed),
    .I2(_140_[0]),
    .I3(_113_[2]),
    .O(_076_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf0ee)
  ) _267_ (
    .I0(_140_[0]),
    .I1(btn_pressed),
    .I2(_154_[0]),
    .I3(_113_[2]),
    .O(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _268_ (
    .I0(_154_[0]),
    .I1(btn_pressed),
    .I2(_141_[0]),
    .I3(_113_[2]),
    .O(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _269_ (
    .I0(_148_[1]),
    .I1(btn_pressed),
    .I2(_127_[0]),
    .I3(_113_[2]),
    .O(_086_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf022)
  ) _270_ (
    .I0(_112_[1]),
    .I1(btn_pressed),
    .I2(_122_[0]),
    .I3(_113_[2]),
    .O(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf0bb)
  ) _271_ (
    .I0(_050_),
    .I1(btn_pressed),
    .I2(_155_[0]),
    .I3(_113_[2]),
    .O(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _272_ (
    .I0(_128_[0]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_123_[1]),
    .I4(_113_[2]),
    .O(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _273_ (
    .I0(_123_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_117_[1]),
    .I4(_113_[2]),
    .O(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _274_ (
    .I0(_116_[0]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_113_[1]),
    .I4(_113_[2]),
    .O(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _275_ (
    .I0(_131_[0]),
    .I1(btn_pressed),
    .I2(data1[0]),
    .I3(_133_[1]),
    .I4(_113_[2]),
    .O(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _276_ (
    .I0(_133_[1]),
    .I1(btn_pressed),
    .I2(data1[1]),
    .I3(_134_[1]),
    .I4(_113_[2]),
    .O(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _277_ (
    .I0(_134_[1]),
    .I1(btn_pressed),
    .I2(data1[3]),
    .I3(_135_[1]),
    .I4(_113_[2]),
    .O(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _278_ (
    .I0(_135_[1]),
    .I1(btn_pressed),
    .I2(data1[3]),
    .I3(_136_[1]),
    .I4(_113_[2]),
    .O(_072_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _279_ (
    .I0(_136_[1]),
    .I1(btn_pressed),
    .I2(data1[4]),
    .I3(_137_[1]),
    .I4(_113_[2]),
    .O(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _280_ (
    .I0(_137_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_138_[1]),
    .I4(_113_[2]),
    .O(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _281_ (
    .I0(_141_[0]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_142_[1]),
    .I4(_113_[2]),
    .O(_079_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _282_ (
    .I0(_142_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_143_[1]),
    .I4(_113_[2]),
    .O(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _283_ (
    .I0(_143_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_144_[1]),
    .I4(_113_[2]),
    .O(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _284_ (
    .I0(_144_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_145_[1]),
    .I4(_113_[2]),
    .O(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _285_ (
    .I0(_145_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_146_[1]),
    .I4(_113_[2]),
    .O(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _286_ (
    .I0(_146_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_147_[1]),
    .I4(_113_[2]),
    .O(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT5 #(
    .INIT(32'd4278248162)
  ) _287_ (
    .I0(_147_[1]),
    .I1(btn_pressed),
    .I2(status[4]),
    .I3(_148_[1]),
    .I4(_113_[2]),
    .O(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/ildus/dev/midi_fpga/env/symbiflow/xc7/conda/envs/xc7/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  LUT6 #(
    .INIT(64'hf7ffffff08000000)
  ) _288_ (
    .I0(_120_[4]),
    .I1(_120_[3]),
    .I2(_120_[2]),
    .I3(_120_[1]),
    .I4(_120_[0]),
    .I5(baud_clk),
    .O(_057_)
  );
  (* keep = 32'd1 *)
  IBUF _289_ (
    .I(btn1),
    .O(_051_)
  );
  (* keep = 32'd1 *)
  IBUF _290_ (
    .I(btn2),
    .O(_052_)
  );
  (* keep = 32'd1 *)
  IBUF _291_ (
    .I(btn3),
    .O(_053_)
  );
  (* keep = 32'd1 *)
  IBUF _292_ (
    .I(btn4),
    .O(_054_)
  );
  (* keep = 32'd1 *)
  IBUF _293_ (
    .I(clk),
    .O(_055_)
  );
  (* keep = 32'd1 *)
  OBUF _294_ (
    .I(_092_),
    .O(led1)
  );
  (* keep = 32'd1 *)
  OBUF _295_ (
    .I(_093_),
    .O(led2)
  );
  (* keep = 32'd1 *)
  OBUF _296_ (
    .I(_050_),
    .O(midi_tx)
  );
  (* keep = 32'd1 *)
  IBUF _297_ (
    .I(rst),
    .O(_150_)
  );
  assign _126_[1] = _113_[2];
  assign { _142_[2], _142_[0] } = { _113_[2], status[4] };
  assign { _133_[2], _133_[0] } = { _113_[2], data1[0] };
  assign { _143_[2], _143_[0] } = { _113_[2], status[4] };
  assign _129_[1] = _113_[2];
  assign { _144_[2], _144_[0] } = { _113_[2], status[4] };
  assign { _123_[2], _123_[0] } = { _113_[2], status[4] };
  assign { _145_[2], _145_[0] } = { _113_[2], status[4] };
  assign { _134_[2], _134_[0] } = { _113_[2], data1[1] };
  assign { _146_[2], _146_[0] } = { _113_[2], status[4] };
  assign _122_[1] = _113_[2];
  assign { _147_[2], _147_[0] } = { _113_[2], status[4] };
  assign _125_[1] = _113_[2];
  assign { _148_[2], _148_[0] } = { _113_[2], status[4] };
  assign _121_[0] = _120_[0];
  assign _149_[1] = _113_[2];
  assign { _135_[2], _135_[0] } = { _113_[2], data1[3] };
  assign _130_[1] = _121_[1];
  assign { _136_[2], _136_[0] } = { _113_[2], data1[3] };
  assign _128_[1] = _113_[2];
  assign { _117_[2], _117_[0] } = { _113_[2], status[4] };
  assign { _137_[2], _137_[0] } = { _113_[2], data1[4] };
  assign _116_[1] = _113_[2];
  assign _131_[1] = _113_[2];
  assign _115_[1] = _113_[2];
  assign { _138_[2], _138_[0] } = { _113_[2], status[4] };
  assign _114_[1] = _113_[2];
  assign _127_[1] = _113_[2];
  assign _113_[0] = status[4];
  assign _153_[0] = btn_reset;
  assign _139_[1] = _113_[2];
  assign _112_[0] = _097_;
  assign _132_[1] = _121_[1];
  assign _001_[3:2] = { _124_[3], _124_[3] };
  assign _140_[1] = _113_[2];
  assign _124_[2:0] = { btn3_pressed, btn_reset, btn4_pressed };
  assign _154_[1] = _113_[2];
  assign _141_[1] = _113_[2];
  assign _155_[1] = _113_[2];
  assign { data1[7:5], data1[2] } = { 2'h0, status[4], data1[3] };
  assign data2 = { 1'h0, status[4], status[4], status[4], status[4], status[4], status[4], status[4] };
  assign { status[7:5], status[3:0] } = { status[4], 1'h0, status[4], 4'h0 };
endmodule
